# Generated by Django 5.2.8 on 2025-11-07 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('mensagem_universo', 'Descubra a Mensagem Oculta do Universo Para Você'), ('dom_espiritual', 'Qual é o Seu Dom Espiritual Escondido?'), ('milagre', 'Que Milagre Está Prestes a Acontecer na Sua Vida?'), ('guia_espiritual', 'Qual é o Seu Guia Espiritual e o Que Ele Quer Te Dizer?'), ('energia_mistica', 'Que Energia Mística Você Atrai?'), ('signo_oculto', 'Descubra Seu Verdadeiro Signo Espiritual')], max_length=50)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('icone', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Testes',
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('respostas', models.JSONField()),
                ('resultado_preview', models.TextField()),
                ('resultado_completo', models.TextField()),
                ('pago', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('teste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testes.teste')),
            ],
            options={
                'verbose_name_plural': 'Respostas',
            },
        ),
    ]
