# Generated by Django 5.2.8 on 2025-11-13 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='pago_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resposta',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=9.9, max_digits=10),
        ),
        migrations.AddField(
            model_name='resposta',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resposta',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resposta',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('cancelled', 'Cancelado')], default='pending', max_length=20),
        ),
    ]
